url: twinbasic.github.io
baseurl: /
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
collections:
  intro:
    output: true
  features:
    output: true
  samples:
    output: true